backend:
  name: git-gateway
  branch: master
media_folder: "source/assets/images/uploads"
public_folder: "/assets/images/uploads"
collections:
  - name: 'posts'
    label: 'Posts'
    label_singular: "Post"
    folder: 'source/_posts'
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
